import { existsSync, readFileSync } from "node:fs";
import { builtinModules } from "node:module";
import { resolve } from "node:path";
import type { Plugin } from "vite-plus";
import { defineConfig } from "vite-plus";

/**
 * Load .env file without external dependencies
 * Returns an object with environment variables from .env file
 */
function loadEnvFile(): Record<string, string> {
	const envPath = resolve(process.cwd(), ".env");
	if (!existsSync(envPath)) return {};

	const env: Record<string, string> = {};
	const content = readFileSync(envPath, "utf-8");
	for (const line of content.split("\n")) {
		const trimmed = line.trim();
		if (!trimmed || trimmed.startsWith("#")) continue;
		const [key, ...valueParts] = trimmed.split("=");
		if (key) env[key.trim()] = valueParts.join("=").trim();
	}
	return env;
}

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY VITE + ROLLDOWN
if you want to view the source, please visit the github repository of this plugin
*/
`;

function bannerPlugin(): Plugin {
	return {
		name: "banner-plugin",
		generateBundle(_options, bundle) {
			for (const chunk of Object.values(bundle)) {
				if (chunk.type === "chunk") {
					chunk.code = banner + chunk.code;
				}
			}
		},
	};
}

export default defineConfig(({ mode }) => {
	const isProd = mode === "production";
	const env = loadEnvFile();
	const pluginDir = env.OBSIDIAN_PLUGIN_DIR;

	// Determine output directory:
	// - Production: always output to project root (safe for CI/CD)
	// - Development: output to vault if OBSIDIAN_PLUGIN_DIR is set, otherwise project root
	const outDir = !isProd && pluginDir ? pluginDir : ".";

	if (!isProd) {
		if (pluginDir) {
			console.log(`[dev] Output to: ${pluginDir}/main.js`);
		} else {
			console.log("[dev] OBSIDIAN_PLUGIN_DIR not set. Output to: ./main.js");
			console.log(
				"[dev] Create .env file with OBSIDIAN_PLUGIN_DIR to enable direct vault output.",
			);
		}
	}

	return {
		// Oxlint の設定はここに置く。ルートに `oxlint.json` を置いても
		// 読まれない（Oxlint が探すのは `.oxlintrc.json`）ため、Vite+ は
		// この lint ブロックを唯一の置き場所として案内している。
		lint: {
			options: {
				// 型情報を要するルール(no-floating-promises 等)を有効にする。
				// 実体は Vite+ 同梱の oxlint-tsgolint、つまり TypeScript 7 の
				// ネイティブ実装で、devDependencies の typescript とは独立に動く。
				typeAware: true,
				// tsgo 自身の型診断も出す。tsc(5.9) と TypeScript 7 の両方の目で
				// 見ることになるので、7 系で初めて壊れる書き方がここで止まる。
				// 詳細は CLAUDE.md の TypeScript 7 の項を参照。
				typeCheck: true,
			},
			// plugins は既定を置き換えてしまうので指定しない。
			// 既定の unicorn / typescript / oxc をそのまま使う。
			categories: {
				correctness: "error",
				suspicious: "warn",
				perf: "warn",
				pedantic: "off",
				style: "off",
			},
			rules: {
				"no-unused-vars": "warn",
				// console.error だけは通す。ユーザーに出す Notice とは別に、
				// 失敗の詳細を開発者コンソールへ残さないと原因が追えない。
				"no-console": ["warn", { allow: ["error"] }],
				"typescript/no-explicit-any": "warn",
				// `new Notice(message)` は Obsidian の公開 API そのもので、
				// 戻り値を捨てるのが正しい使い方。副作用のための new を
				// 咎めるこのルールとは噛み合わない。
				"no-new": "off",
			},
			overrides: [
				{
					// ビルド設定の console.log は開発者への出力先案内であって、
					// プラグイン本体に混ざるログとは事情が違う。
					files: ["vite.config.ts"],
					rules: { "no-console": "off" },
				},
				{
					// テストダブルは意図して部分実装なので、`as unknown as T` で
					// 本物の型を名乗らせるのがこのリポジトリの定石。ここで
					// この規則を守らせても、実装のない残りを埋める作業が増えるだけ。
					files: ["src/**/*.test.ts"],
					rules: { "typescript/no-unsafe-type-assertion": "off" },
				},
			],
			// main.js と coverage/ は .gitignore 済みで Oxlint が自動で外す。
			// リリース用スクリプトだけは追跡下にあるので明示的に外す。
			ignorePatterns: ["version-bump.mjs"],
		},
		plugins: [bannerPlugin()],
		build: {
			outDir,
			emptyOutDir: false,
			lib: {
				entry: "src/main.ts",
				formats: ["cjs"],
				fileName: () => "main.js",
			},
			sourcemap: isProd ? false : "inline",
			minify: isProd,
			rollupOptions: {
				external: [
					"obsidian",
					"electron",
					"@codemirror/autocomplete",
					"@codemirror/collab",
					"@codemirror/commands",
					"@codemirror/language",
					"@codemirror/lint",
					"@codemirror/search",
					"@codemirror/state",
					"@codemirror/view",
					"@lezer/common",
					"@lezer/highlight",
					"@lezer/lr",
					...builtinModules,
				],
				output: {
					entryFileNames: "main.js",
				},
			},
		},
		test: {
			globals: true,
			environment: "node",
			include: ["src/**/*.test.ts"],
			coverage: {
				provider: "v8",
				reporter: ["text", "json", "html"],
				// Report every source file, not only the ones a test happened to
				// import. Without this the untested modules are simply absent and
				// the summary reads 100%, which is the opposite of the point.
				all: true,
				include: ["src/**/*.ts"],
				exclude: ["src/**/*.test.ts"],
			},
			server: {
				deps: {
					external: ["obsidian"],
				},
			},
		},
	};
});
